### ISSUE TITLE
ttf2bmp.py 실행 문제 문의

### ISSUE THREAD

**Issue by sugodori** [sukso96100/amazfit-bip-kr#1]
안녕하세요. 최근에 Amazfit bip유저가 된 윤가현 이라고합니다.
먼저 한글화 펌웨어와 방법을 공개해주셔서 감사합니다. 저는 이번에 한글화를 계기로 파이썬을 배우고 있습니다.
----
sukso님께서 Github에 올려주신 ttf2bmp.py로 한글 font 추가하려는 과정에서 자꾸 에러가 발생합니다.

먼저 ttf2bmp.py를 수정한 것입니다.
![ttf2bmp](https://user-images.githubusercontent.com/37901908/38174226-18c166f4-3605-11e8-9fd4-94a5dacce2ac.JPG)
글씨체를 NotoSans CJK kr로 하였습니다.

그 후 ttf2bmp.py를 실행시켰는데 자꾸 아래와 같은 에러가 발생합니다.
![cmd1](https://user-images.githubusercontent.com/37901908/38174248-63a966b2-3605-11e8-8606-94d1f183234f.JPG)

그래서 pip3 install pillow 명령어를 실행시켰지만 이미 설치되어있다는 아래와 같은 메세지가 뜹니다.
![cmd2](https://user-images.githubusercontent.com/37901908/38174260-960e84d4-3605-11e8-8ce8-de28464e30ef.JPG)

아직 파이썬에 입문한지 얼마 되지 않아 미숙하지만 계속 공부하고 있습니다.
바쁘시겠지만 도와주신다면 큰 힘이 될것 같습니다!
감사합니다!

**Comment by sukso96100** [comment]
안녕하세요. 먼저 아래 명령을 실행하여 사용중인 Python 버전을 확인해 보세요. 제가 작성한 스크립트는 Python 3 버전대 기준으로 작성했습니다.
```
python --version
```
아래와 같이 2 버전대로 나오는 경우
```
Python 2.7.10
```

다음과 같이 `python3` 로 스크립트를 실행하도록 해보세요.

```
python3 ttf2bmp.py
```
